Adding data type information for data-driven intents.
FDC3/Intents pull request #5
Opened 2018-10-02 18:26 UTC by nkolba

This PR is to address the handling of data-driven intents that can be raised in current API draft spec.  By providing a place to specify type for both payload of input and output of an  intent, we give the scaffolding for desktop agents to perform the following functions:

- Manage the timing of resolving the Promise for a raised intent.  If an intent has no data payload, it should be resolved as soon as it is routed.  If an intent has a data return defined, the desktop agent should wait to resolve until the handling app has returned the (valid) data.
- Validate data payloads, both when an intent is raised and is being routed (if there is a type specified for the input), and when resolving.

2018-10-03 08:46 UTC, rikoe requested changes

2018-10-03 08:46 UTC, rikoe commented on src/Intent.yaml
> +      If this value is set, the desktop agent can manage the resolution of the intent accordingly.
I am not a fan of this. The difference between a data-driven intent and fire-and-forget intent is then implicit based on whether this property is present or not. Lots of opportunity for misunderstanding.

I would like it to be more explicit: An "intentType" of some kind that indicates the difference, or at the top level a different object for "intent".

2018-10-03 08:46 UTC, rikoe commented on src/Intent.yaml
> +      If this value is set, the desktop agent can manage the validation and resolution of the intent accordingly.
This is a major divergence from the spec so far. We currently use the "contexts" array for the purpose of specifying the possible "input types" (plural) that an intent can accept/operate on. How do these two interact?

2018-10-03 08:46 UTC, rikoe commented on Specification-Draft.MD
> +    * Workflows should not require callbacks or endpoints to maintain references to each other.  With the exception of specifically data-driven intents, once an intent is passed to an endpoint - it c
Just saying this isn't enough, in my opinion. The doc needs to clearly set out the difference between the two.

2018-10-03 11:07 UTC, espenove reviewed
I rather we follow the approach used by Android Intents, where the initiating application uses a separate API when a result is wanted:

No result: startActivity()
Wait for result: startActivityForResult()  

https://developer.android.com/guide/components/intents-filters

2018-10-04 11:55 UTC, espenove commented
Discussed on Intents WG meeting - https://finosfoundation.atlassian.net/wiki/spaces/FDC3/pages/553746496/2018-10-03+Meeting+agenda
Agreed to not move forward with proposed change

2018-10-04 11:55 UTC, closed without merging